import Head from 'next/head'
import { Poppins } from '@next/font/google'
import Home from './Home'
import Navbar from './components/Navbar'

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export default function index() {
  return (
    <>
      <Head>
        <title>Dimsum Place</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.variable} font-poppins`}>
        <div>
          <Navbar />
          <Home />
        </div>
      </main>
    </>
  )
}
